# open3d_loc launch for G1 — ICP global localization against pre-built PCD
# Original: deepglint/open3d_loc/launch/open3d_loc_g1.launch.py (ROS2 Humble)

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    open3d_loc_share = FindPackageShare('open3d_loc')

    use_sim_time_arg = DeclareLaunchArgument(
        'use_sim_time',
        default_value='false',
        description='Use simulation time'
    )

    config_file = PathJoinSubstitution([
        open3d_loc_share, 'config', 'loc_param_g1.yaml'
    ])

    # G1: path to the PCD map generated by FAST-LIO mapping (Track 1a)
    map_file = '/root/maps/scans_0518.pcd'

    # Static TF: odom -> camera_init (FAST-LIO world frame)
    static_tf_camera_init2odom = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='camera_init2odom',
        arguments=['0', '0', '0', '0', '0', '0', '1', 'odom', 'camera_init']
    )

    # Static TF: imu_link -> base_link
    static_tf_imulink2baselink = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='imulink2baselink',
        arguments=['0', '0', '0', '0', '0', '0', '1', 'imu_link', 'base_link']
    )

    # Static TF: base_link -> motion_link (G1 motion control point)
    static_tf_base_center = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='base_center_broadcaster',
        arguments=['0', '0', '0', '0', '0', '0', '1', 'base_link', 'motion_link']
    )

    # Global localization: ICP registration of current scan against pre-built PCD
    global_localization_node = Node(
        package='open3d_loc',
        executable='global_localization_node',
        name='global_localization_node',
        output='screen',
        parameters=[
            config_file,
            {
                'path_map': map_file,
                # G1: tuned ICP and localization parameters
                'pcd_queue_maxsize': 10,
                # G1: voxelsize_coarse must be >= 0.15 for 8M-point PCD (0.01 causes empty voxels)
                'voxelsize_coarse': 0.15,
                'voxelsize_fine': 0.1,
                'threshold_fitness': 0.5,
                'threshold_fitness_init': 0.5,
                'loc_frequence': 2.5,
                'save_scan': False,
                'hidden_removal': False,
                'maxpoints_source': 80000,
                'maxpoints_target': 400000,
                'filter_odom2map': False,
                'kalman_processVar2': 0.001,
                'kalman_estimatedMeasVar2': 0.02,
                'confidence_loc_th': 0.7,
                'dis_updatemap': 3.5,
                'use_sim_time': LaunchConfiguration('use_sim_time'),
            },
        ],
    )

    return LaunchDescription([
        use_sim_time_arg,
        static_tf_camera_init2odom,
        static_tf_imulink2baselink,
        static_tf_base_center,
        global_localization_node,
    ])
